name: Pantheon Domain Masking
on:
  push:

jobs:
  linting:
    name: Code linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Composer install
        run: composer install

      - name: Code sniff
        run: composer run-script codesniff

      - name: Code lint
        run: composer run-script code:lint
