name: Pantheon Domain Masking
on:
  push:

jobs:
  phpcompatibility:
    runs-on: ubuntu-latest
    name: PHP Compatibility
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: PHPCompatibility
        uses: pantheon-systems/phpcompatibility-action@v1
        with:
          test-versions: 7.4-
  linting:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pantheon-public/build-tools-ci:8.x-php8.1
      options: --user root
    name: Code linting
    env:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
      TERM: dumb
      TERMINUS_TOKEN: ${{ secrets.TERMINUS_TOKEN }}
      TERMINUS_SITE: ${{ secrets.TERMINUS_SITE }}
      TERMINUS_ORG: ${{ secrets.TERMINUS_ORG }}
      GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
      GITHUB_RUN_NUMBER: ${{ github.run_number }}
      COMMIT_SHA: ${{ github.sha }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SANDBOX_SSH_KEY: ${{ secrets.SANDBOX_SSH_KEY }}
      BASH_ENV: ~/.bashrc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Composer install
        run: composer install
      - name: Code sniff
        run: composer run-script codesniff